<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" data-action="navigation">
  <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
    <?= /* @escapeNotVerified */ $_menu ?>
    <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
    <li class="level0 nav-7 category-item last  level-top ui-menu-item" role="presentation">
      <a href="/" class="level-top ui-corner-all" id="ui-id-8" tabindex="-1" role="menuitem">
        <span>Home</span>
      </a>
    </li>
  </ul>
</nav>